config:
  temporalHost: "temporal-frontend.temporal.svc.cluster.local:7233"
  temporalNamespace: "default"
  segmentsManagerUrl: "http://segments-manager.segments-manager.svc.cluster.local:8000"
  domain: "domain1"
image:
  repository: ghcr.io/team-redbull/workflows-orchestrator
  tag: v0.1.26
  pullPolicy: IfNotPresent
replicas: 2
workflowsApi:
  replicas: 2
  port: 8080
  route:
    host: ""
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
