apiVersion: v1
kind: ServiceAccount
metadata:
  name: segment-lifecycle-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-lifecycle-worker
  labels:
    app: segment-lifecycle-worker
spec:
  replicas: {{ .Values.activityWorker.replicas }}
  selector:
    matchLabels:
      app: segment-lifecycle-worker
  template:
    metadata:
      labels:
        app: segment-lifecycle-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: segment-lifecycle-worker
      containers:
        - name: segment-lifecycle-worker
          image: "{{ .Values.activityWorker.image.repository }}:{{ .Values.activityWorker.image.tag }}"
          imagePullPolicy: {{ .Values.activityWorker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: workflows-orchestrator-config
            - configMapRef:
                name: segment-lifecycle-config
            - secretRef:
                name: {{ .Values.secrets.existingSecret | default "segments-manager-token" }}
            - secretRef:
                name: {{ .Values.secrets.existingDay1Secret | default "day1-git-token" }}
