{{- if not .Values.ingestToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collector.tokenSecret" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ingestToken.key }}: {{ required "ingestToken.value or ingestToken.existingSecret is required" .Values.ingestToken.value | quote }}
{{- end }}
