{{- if .Values.ghcrPullSecret.enabled }}
{{- $secret := .Values.ghcrPullSecret }}
{{- $auth := printf "%s:%s" $secret.username $secret.password | b64enc }}
{{- $dockerconfigjson := dict "auths" (dict $secret.registry (dict "username" $secret.username "password" $secret.password "auth" $auth)) | toJson }}
{{- range $secret.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/managed-by: helmfile
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | b64enc }}
---
{{- end }}
{{- end }}
