config:
  day1RepoUrl: "https://github.com/team-redbull/gitops-day1-platform-config.git"
  day1Branch: "main"
  dhcpApiUrl: "http://dhcp-scope-manager.dhcp-scope-manager.svc.cluster.local:8080"
  dhcpExclusionOctetRanges:
    HC:
      - [1, 10]
      - [241, 254]
secrets:
  existingSecret: "segments-manager-token"
  segmentsManagerApiToken: "dev-token"
  existingDay1Secret: "day1-git-token"
  day1GitToken: "dev-token"
activityWorker:
  image:
    repository: ghcr.io/team-redbull/segment-lifecycle-worker
    tag: v0.1.34
    pullPolicy: IfNotPresent
  replicas: 2
