apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redfish.fullname" . }}-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "redfish.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redfish.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "redfish.fullname" . }}
    namespace: {{ .Release.Namespace }}
