apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "redfish.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
