apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redbull-platform
  namespace: openshift-gitops
spec:
  sourceRepos:
    - "*"
  sourceNamespace:
    - openshift-gitops
  destinations:
    - name: "*"
      namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"