apiVersion: v1
kind: ConfigMap
metadata:
  name: workflows-orchestrator-config
data:
  TEMPORAL_HOST: {{ .Values.config.temporalHost | quote }}
  TEMPORAL_NAMESPACE: {{ .Values.config.temporalNamespace | quote }}
  DOMAIN: {{ .Values.config.domain | quote }}
  SEGMENTS_MANAGER_URL: {{ .Values.config.segmentsManagerUrl | quote }}
