apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-orchestrator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-orchestrator
  labels:
    app: workflows-orchestrator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: workflows-orchestrator
  template:
    metadata:
      labels:
        app: workflows-orchestrator
    spec:
      serviceAccountName: workflows-orchestrator
      containers:
        - name: workflows-orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: workflows-orchestrator-config
