apiVersion: v1
kind: Service
metadata:
  name: {{ include "navigator.name" . }}
  labels:
    {{- include "navigator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "navigator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "navigator.name" . }}
  labels:
    {{- include "navigator.labels" . | nindent 4 }}
spec:
  {{- with .Values.route.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "navigator.name" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
